BingoVega.FrontEnd/Models/HomeViewModel.cs
using BingoVega.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BingoVega.FrontEnd.Models
{
    public class HomeViewModel
    {
        public List<BigoRoom> BingoRooms { get; set; }
    }
}

BingoVega.FrontEnd/Controllers/HelpController.cs
using BingoVega.FrontEnd.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using BingoVega.FrontEnd.Utils;

namespace BingoVega.FrontEnd.Controllers
{
    public class HelpController : Controller
    {
        private readonly ILogger<HelpController> _logger;

        public HelpController(ILogger<HelpController> logger)
        {
            ViewBag.isLogin = true;            
            _logger = logger;
        }

        public IActionResult ContactUs()
        {

            return View();
        }
        public IActionResult Faq()
        {
            return View();
        }
        public IActionResult PrivacyPolicy()
        {
            return View();
        }
        public IActionResult TermsConditions()
        {
            return View();
        }
        public IActionResult ResponsibleGaming()
        {
            return View();
        }
        public IActionResult Security()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

BingoVega.FrontEnd/Controllers/HomeController.cs
using BingoVega.FrontEnd.Models;
using BingoVega.FrontEnd.Utils;
using BingoVega.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Http.Features;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Threading.Tasks;


namespace BingoVega.FrontEnd.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private IConfiguration _config;

        public HomeController(ILogger<HomeController> logger, IConfiguration config)
        {
            _logger = logger;
            _config = config;
        } 
        
        public IActionResult Index(string affid, string cxd)
        {           
            string ip = DataPrepare.getRouterIpAddress();           
            saveIp(ip);
            saveCountry(ip);
            saveCxdAndAffid(affid, cxd);
           
            return View();
        }     

        private void saveCxdAndAffid(string affid, string cxd)
        {
            if (!String.IsNullOrEmpty(cxd))
            {
                if (DataPrepare.isAValidCxd(cxd))
                {
                    Utils.Cookie.save(Response, "cxd", cxd);

                    String affiliate = DataPrepare.getAffid(affid, cxd);
                    Utils.Cookie.save(Response, "affiliateid", affiliate);
                }
            }
        }

        private void saveIp(String ip)
        {
            if (!String.IsNullOrEmpty(ip)) Utils.Cookie.save(Response, "ipCliente", ip);
        }

        private void saveCountry(string ip)
        {
            string country = DataPrepare.getCountryByIpAddress(ip);
            if (!String.IsNullOrEmpty(country)) Utils.Cookie.save(Response, "country", country);
        }

         public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult Promotions()
        {
            return View();
        }

        public IActionResult DepositBonuses()
        {
            return View();
        }

        public IActionResult RulerGalaxy()
        {
            return View();
        }

        public IActionResult Loyalty()
        {            
            return View();
        }

        public IActionResult ReferFriend()
        {
            return View();
        }

        public IActionResult CasinoCashBack()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

BingoVega.FrontEnd/Controllers/LobbyGamesController.cs
using BingoVega.FrontEnd.Models;
using BingoVega.FrontEnd.Utils;
using BingoVega.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace BingoVega.FrontEnd.Controllers
{
    public class LobbyGamesController : Controller
    {
        private readonly ILogger<LobbyGamesController> _logger;
        private IConfiguration _config;

        public LobbyGamesController(ILogger<LobbyGamesController> logger, IConfiguration config)
        {
            _logger = logger;
            _config = config;
        }

        public IActionResult SlotsGames()
        {            

            ViewBag.Message = true;
            BingoRoomViewModel room = new BingoRoomViewModel();
            room.TextForMarquee = Api.GetTextforBingoRoomMarquee();
            return View(room);
        }

        public IActionResult VideoPokerGames()
        {
            ViewBag.Message = true;
            BingoRoomViewModel room = new BingoRoomViewModel();
            room.TextForMarquee = Api.GetTextforBingoRoomMarquee();
            return View(room);
        }

        public IActionResult BingoRooms()
        {
            BingoRoomViewModel room = new BingoRoomViewModel();
            room.HasFullLobbyAccess = Api.GetLobbyAccessLevel(_config, HttpContext);
            room.Rooms =  Api.GetBingoRooms();
            room.TextForMarquee = Api.GetTextforBingoRoomMarquee();
            room.UserId = Session.getCurrentUserId(HttpContext); 
            (room.Token, room.JsessionId) = Api.GetUserCredentialsForBingoRooms(room.UserId);
            return View(room);
        }

        public IActionResult PreOrderCards(string roomId)
        {//test
            BingoRoomViewModel room = new BingoRoomViewModel();    
            string userId = Session.getCurrentUserId(HttpContext);           
            (string token, string jsessionId) = Api.GetUserCredentialsForBingoRooms(userId);
            room.UrlForPreOrderCards= string.Format("https://play.bngvg.com/preorder/{0}/{1}/{2}/{3}", roomId, userId, token, jsessionId);
            return View(room);
        }
               
    }
}

BingoVega.FrontEnd/Views/Home/CasinoCashBack.cshtml
@{
    bool isLogedIn = Session.isUserLogedIn(Context);
}

@using Microsoft.AspNetCore.Http
@using BingoVega.FrontEnd.Utils
@{
    ViewData["Title"] = "Casino Cash Back";
}
<h1 class="sectionsTitle">@ViewData["Title"]</h1>
<div class=" mt-3 rounded-mix p-5 planetary-bg">
    <div class="whiteBoxContent">
        <p>Play any of your favorite games between Monday and Thursday and if you finish the week with a losing record, we will credit you with 10% of your losses as a bonus, up to $100 so you can get back to spinning and winning.</p>

        <strong>Terms and Conditions</strong>
        <ul>
            <li>Casino Cash Back Bonus is calculated from Monday 12:01 AM EST to Thursday 11:59 PM EST</li>
            <li>Player must submit a support ticket on Thursdays no later than 11:59 PM  to claim their Casino Cash Back Bonus</li>
            <li>There is a 45x wagering requirement on all Casino Cash Back Bonuses.</li>
            <li>Player cannot have a pending withdrawal</li>
            <li>If a player received a withdrawal within the week a claim for cash back bonus cannot be made.</li>
            <li>Player balance must be 0</li>
        </ul>
        <div class="d-flex justify-content-center my-4">
            @if (isLogedIn)
            {
                <a asp-controller="LobbyGames" asp-action="BingoRooms"  type="button" class="btn btn-warning fw-bold p-3 text-uppercase">Play Now</a>
            }
            else
            {
                <button data-bs-toggle="modal" data-bs-target="#loginModal" type="button" class="btn btn-warning fw-bold p-3 text-uppercase">Play Now</button>
            }
        </div>
    </div>
</div>

BingoVega.FrontEnd/Views/Home/DepositBonuses.cshtml
@{
    bool isLogedIn = Session.isUserLogedIn(Context);
}

@using Microsoft.AspNetCore.Http
@using BingoVega.FrontEnd.Utils
@{
    ViewData["Title"] = "Deposit Bonuses";
}
<h1 class="sectionsTitle">@ViewData["Title"]</h1>
<div class="mt-3 rounded-mix p-5 planetary-bg">
    <div class="whiteBoxContent">
        <h3>WEEKDAY BONUS</h3>
        <p>
            Offer valid from Mondays 12:00am Through Thursdays 11:59pm
        </p>
        <ul>
            <li>Up to $49 – 200%</li>
            <li>$50 to $99 – 300%</li>
            <li>$100+ – 500%</li>
            <li>$200+ – 700%</li>
        </ul>
        <div class="alert alert-secondary" role="alert">
            WEEKDAY MULTIPLIER BONUS: – Multiple deposits in a single day are elegible for the multiplier. – Second deposits of any value add 50% to qualifying bonus. – Third deposits of any value add 100% to qualifying bonus. Note: Cannot be combined with any other offer.
        </div>
        <div class="d-flex justify-content-center my-4">
            @if (isLogedIn)
            {
                <a asp-controller="LobbyGames" asp-action="BingoRooms" type="button" class="btn btn-warning fw-bold p-3 text-uppercase">Play Now</a>
            }
            else
            {
                <button data-bs-toggle="modal" data-bs-target="#loginModal" type="button" class="btn btn-warning fw-bold p-3 text-uppercase">Play Now</button>
            }
        </div>
    </div>
    <div class="whiteBoxContent" id="weekends">
        <h3>WEEKEND BONUS</h3>
        <p>
            Offer valid from Friday 12:00 AM to Sunday 11:59 PM.
        </p>
        <ul>
            <li>Up to $49 – 200%</li>
            <li>$50 – $99 – 350%</li>
            <li>$100+ – 600%</li>
            <li>$200+ – 800%</li>
        </ul>
        <div class="alert alert-secondary" role="alert">
            WEEKEND MULTIPLIER BONUS: – Multiple deposits in a single day are elegible for the multiplier. – Second deposits of any value add 100% to qualifying bonus. Third deposits of any value add 200% to qualifying bonus. Note: Cannot be combined with any other offer.
        </div>
        <div class="d-flex justify-content-center my-4">
            @if (isLogedIn)
            {
                <a asp-controller="LobbyGames" asp-action="BingoRooms" type="button" class="btn btn-warning fw-bold p-3 text-uppercase">Play Now</a>
            }
            else
            {
                <button data-bs-toggle="modal" data-bs-target="#loginModal" type="button" class="btn btn-warning fw-bold p-3 text-uppercase">Play Now</button>
            }
        </div>
    </div>
    <div class="alert alert-primary text-center my-5" role="alert">
        To receive your extra bonus, please submit a ticket to support requesting your extra bonus. You must claim within 30 minutes of your deposit. Just click on the support tab, contact us, complete the ticket and click submit.
    </div>
</div>

BingoVega.FrontEnd/Views/Home/Index.cshtml
@*@model BingoVega.FrontEnd.Models.HomeViewModel*@

@{
    ViewData["Title"] = "HomePage";
}
<div>
    <a href="/SignUp/SignUp"><img src="/images/registerBanner.png" class="d-block w-100" alt="..."></a>
</div>
<div id="carouselSlider" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-inner">
        <div class="carousel-item active">
            <a href="/html/lp/2021/december/xmas-tree.html" target="_blank"><img src="/images/promotions/2021/december/homeSlider/promo-1-tree.png" class="d-block w-100" alt="..."></a>
        </div>
        <div class="carousel-item">
            <a href="/Home/Promotions/#santabb"><img src="/images/promotions/2021/december/homeSlider/promo-2-santa-bb.png" class="d-block w-100" alt="..."></a>
        </div>
        <div class="carousel-item">
            <a href="/Home/Promotions/#party"><img src="/images/promotions/2021/december/homeSlider/promo-3-xmas-party.png" class="d-block w-100" alt="..."></a>
        </div>
        <div class="carousel-item">
            <a href="/html/lp/2021/december/new-year.html" target="_blank"><img src="/images/promotions/2021/december/homeSlider/promo-5-new-year-banner.png" class="d-block w-100" alt="..."></a>
        </div>
        <div class="carousel-item">
            <a href="/Home/Promotions/#saturday"><img src="/images/promotions/2021/december/homeSlider/promo-6-saturday-night.png" class="d-block w-100" alt="..."></a>
        </div>
        <div class="carousel-item">
            <a href="/html/lp/2021/december/xmas-slots.html" target="_blank"><img src="/images/promotions/2021/december/homeSlider/promo4-xmas-tourney.png" class="d-block w-100" alt="..."></a>
        </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselSlider" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselSlider" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
</div>
<div id="latestWinners" class="row">
    <div class="col-sm-12 col-lg-12 col-12 mt-3">
        <div class="latestWinnersContent ">
            <div class="row">
                <div class="col-12 col-sm-12 col-lg-12">
                    <img src="/images/testimonials.png" style="width:100%; max-width:1200px; height:auto;" />

                </div>
            </div>
        </div>
    </div>
</div>
<div id="bingoRooms" class="col-sm-12 col-lg-12 col-12">
    <h4 class="bingoTitles h4 text-center text-uppercase text-white fw-bolder p-2">Bingo Rooms</h4>
    <div class="bg-white rounded-bg p-3 col-sm-12 col-lg-12 col-12">
        <div class="row justify-content-center">
            <div class="col-sm-3 col-lg-3 col-12">
                <div class="bingoRooms">
                    <div class="bingoRoomImg">
                        <img src="/assets/milky_way.jpg" />
                    </div>
                    <div class="bingoRoomBody">
                        <div class="diver"></div>
                        <h4>Milky Way</h4>
                        <h5>Schedule</h5>
                        <p>Monday - Thursday 10am-12am<br>
                        Friday - Sunday 10am-2am</p>
                        <h5>Card Cost Range</h5>
                        <p>$0.25 - $1.00</p>
                        <div class="bingoRoomFooter">
                            <a class="btn btn-secondary bingoRoomBtn " href="/SignUp/SignUp" data-bs-toggle="modal" data-bs-target="#loginModal">Click to Join</a>
                        </div>
                    </div>

                </div>
            </div>
            <div class="col-sm-3 col-lg-3 col-12">
                <div class="bingoRooms">
                    <div class="bingoRoomImg">
                        <img src="/assets/big_asteroids.jpg" />
                    </div>
                    <div class="bingoRoomBody">
                        <div class="diver"></div>
                        <h4>Big Asteroids</h4>
                        <h5>Schedule</h5>
                        <p>Monday - Thursday<br />7pm-9pm</p>
                        <h5>Card Cost Range</h5>
                        <p>$.05 - $1.00</p>
                        <p></p>
                        <div class="bingoRoomFooter">
                            <a class="btn btn-secondary bingoRoomBtn " href="/SignUp/SignUp">Click to Join</a>
                        </div>
                    </div>

                </div>
            </div>
            <div class="col-sm-3 col-lg-3 col-12">
                <div class="bingoRooms">
                    <div class="bingoRoomImg">
                        <img src="/assets/little_dipper.jpg" />
                    </div>
                    <div class="bingoRoomBody">
                        <div class="diver"></div>
                        <h4>Little Dipper</h4>
                        <h5>Schedule</h5>
                        <p>Monday - Sunday<br />12am-12pm EST</p>
                        <h5>Card Cost Range</h5>
                        <p>$0.05 - $0.15</p>
                        <div class="bingoRoomFooter">
                            <a class="btn btn-secondary bingoRoomBtn " href="/SignUp/SignUp">Click to Join</a>
                        </div>
                    </div>

                </div>
            </div>
            <div class="col-sm-3 col-lg-3 col-12">
                <div class="bingoRooms">
                    <div class="bingoRoomImg">
                        <img src="/assets/asteroids.jpg" />
                    </div>
                    <div class="bingoRoomBody">
                        <div class="diver"></div>
                        <h4>ASTEROIDS</h4>
                        <h5>Schedule</h5>
                        <p>Friday and Saturday 8pm-1Opm<br />Sunday 6pm - 8pm</p>
                        <h5>Card Cost</h5>
                        <p>$0.65 - $1.50</p>
                        <div class="bingoRoomFooter">
                            <a class="btn btn-secondary bingoRoomBtn " href="/SignUp/SignUp">Click to Join</a>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
    <div id="slotGames">
        <h4 class="bingoTitles h4 text-center text-uppercase text-white fw-bolder p-2">Newest SLOT GAMES</h4>
        <div class="gradient-bg rounded-top p-5 col-sm-12 col-lg-12 col-12 text-white">
            Visit the casino where you can spin to win on over 100 slot games!! <span class="text-yellow">Progressive Jackpots, Missions with $$ Rewards and Video Poker!!!</span>
            <h2 class="fw-bolder text-uppercase text-center mt-5">More than <span class="text-yellow">$200,000</span> in slots jackpots</h2>
            <div id="slotsHP">
                <div class="row">
                    <div class="col-6 col-sm-4 col-lg-3">
                        <img src="/images/casino/slots/fruit-serenity.png" />
                        <h4>Fruit Serenity</h4>
                        <a class="btn btn-primary px-5 text-bold" data-bs-toggle="modal" data-bs-target="#loginModal">Play Now</a>
                    </div>
                    <div class="col-6 col-sm-4 col-lg-3">
                        <img src="/images/casino/slots/catch-release.png" />
                        <h4>Catch & Release</h4>
                        <a class="btn btn-primary px-5 text-bold" data-bs-toggle="modal" data-bs-target="#loginModal">Play Now</a>
                    </div>
                    <div class="col-6 col-sm-4 col-lg-3">
                        <img src="/images/casino/slots/the-golden-inn.png" />
                        <h4>The Golden Inn</h4>
                        <a class="btn btn-primary px-5 text-bold" data-bs-toggle="modal" data-bs-target="#loginModal">Play Now</a>
                    </div>
                    <div class="col-6 col-sm-4 col-lg-3">
                        <img src="/images/casino/slots/the-forbbiden-tomb.png" />
                        <h4>The Forbidden Tomb</h4>
                        <a class="btn btn-primary px-5 text-bold" data-bs-toggle="modal" data-bs-target="#loginModal">Play Now</a>
                    </div>
                    <div class="col-6 col-sm-4 col-lg-3">
                        <img src="/images/casino/slots/kitty-cutie.png" />
                        <h4>Kitty Cutie</h4>
                        <a class="btn btn-primary px-5 text-bold" data-bs-toggle="modal" data-bs-target="#loginModal">Play Now</a>
                    </div>
                    <div class="col-6 col-sm-4 col-lg-3">
                        <img src="/images/casino/slots/12-animals.png" />
                        <h4>12 Animals</h4>
                        <a class="btn btn-primary px-5 text-bold" data-bs-toggle="modal" data-bs-target="#loginModal">Play Now</a>
                    </div>
                    <div class="col-6 col-sm-4 col-lg-3">
                        <img src="/images/casino/slots/blade-of-the-abyss.png" />
                        <h4>Blade of the Abyss</h4>
                        <a class="btn btn-primary px-5 text-bold" data-bs-toggle="modal" data-bs-target="#loginModal">Play Now</a>
                    </div>
                    <div class="col-6 col-sm-4 col-lg-3">
                        <img src="/images/casino/slots/candy-cash-deluxe.png" />
                        <h4>Candy Cash Deluxe</h4>
                        <a class="btn btn-primary px-5 text-bold" data-bs-toggle="modal" data-bs-target="#loginModal">Play Now</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-12 col-sm-12 col-lg-12">
            <a class="btn text-center text-white col-sm-12 btn-purple rounded-bot" href="/Games/Slots">View all</a>
        </div>
    </div>
    <div id="welcome" class="bg-white mt-3 rounded-mix p-5 planetary-bg">
        <h2 class="text-center text-uppercase fw-bold">Welcome to <span class="text-secondary">BingoVega</span>.com!</h2>
        <div class="fw-bold text-body text-left">
            <p>At Bingo Vega players can play bingo games, casino games, bonus slots, and more for real cash prizes. Our players win more often and win bigger prizes than on any other online bingo site out there on the web. With over 50,000 players, Bingo Vega has been the web’s trusted site for online bingo since 1999.</p>

            <p>BingoVega offers new games every hour, chat game prizes, and new promotions every month. Watch your cards fill up and your winnings grow while making friends from all around the world. Laugh, play, and win here with us at Bingo Vega.</p>

            <p>Create an account today and enter the fun-filled community of Bingo Vega.  Joining is easy, secure, and completely free. In just 5 minutes, you could be playing exhilarating online games from the comfort of your own home.</p>
        </div>
        <div class="col-12 col-sm-12 col-lg-12" id="welcomeBtn">
            <p class="text-center">
                <img class="shoupe d-none d-sm-block" src="/images/shoupe.png" />
                <a class="btn btn-primary purple-btn" asp-area="" asp-controller="Help" asp-action="Faq">Click HERE for More information</a>
            </p>
        </div>
    </div>
</div>

BingoVega.FrontEnd/Views/Home/Loyalty.cshtml
@{
    ViewData["Title"] = "Loyalty";
}
<h1 class="sectionsTitle">@ViewData["Title"]</h1>
<div class="mt-3 rounded-mix p-5 planetary-bg">
    <div class="whiteBoxContent">
        COMING SOON!
    </div>
    </div>

BingoVega.FrontEnd/Views/Home/ReferFriend.cshtml
@{
    ViewData["Title"] = "Refer a Friend";
}
<h1 class="sectionsTitle">@ViewData["Title"]</h1>
<div class="bg-white mt-3 rounded-mix p-5 planetary-bg">
    CONTENT HERE
</div>

BingoVega.FrontEnd/Views/Home/RulerGalaxy.cshtml
@{
    bool isLogedIn = Session.isUserLogedIn(Context);
}

@using Microsoft.AspNetCore.Http
@using BingoVega.FrontEnd.Utils
@{
    ViewData["Title"] = "Ruler of the Galaxy";
}
<h1 class="sectionsTitle">@ViewData["Title"]</h1>
<div class="mt-3 rounded-mix p-5 planetary-bg">
    <div class="whiteBoxContent">
        <p style="text-align:center"><img src="https://bingovega.com/wp-content/themes/bingovega/images/desposit-now.png" /></p>
        <h3>Ruler of the Galaxy</h3>
        <p>
            All roomies are special but WHO will be our “Ruler of the Galaxy” this month? It could be YOU! With this honor comes some special gifts and a special duty! PLAY BINGO!! Every time the “Ruler of the Galaxy ” is in chat and wins a bingo, all active players in chat who shout, “Long Live the Ruler:” win 2BB!!! On top of the special gifts, the “Ruler” will also have a bingo pattern named in their honor, and if he/she bingos on the special pattern, ca-ching, 3bb for all the active roomies!!
        </p>
        <div class="alert alert-danger" role="alert">
            <h4 class="alert-heading text-center">DORYLEE!!!!!!</h4>
            <p style="text-align:center">Our December Ruler of the Galaxy</p>
            <hr>
            <h4 class="alert-heading text-center text-uppercase">Congratulations</h4>
        </div>
        <p>
            In addition to all her goodies, be sure to watch for her special pattern because when she bingos on her pattern, the roomies win!!
        </p>
        <div class="d-flex justify-content-center my-4">
            @if (isLogedIn)
            {
                <a asp-controller="LobbyGames" asp-action="BingoRooms" type="button" class="btn btn-warning fw-bold p-3 text-uppercase">Play Now</a>
            }
            else
            {
                <button data-bs-toggle="modal" data-bs-target="#loginModal" type="button" class="btn btn-warning fw-bold p-3 text-uppercase">Play Now</button>
            }
        </div>
    </div>
</div>